version: "3"


services:
    servicio1:
        build: ./microservicio1
        depends_on: 
            - mongo
        environment: 
            - PORT=5000
            - MONGO_URI=mongodb://mongo:27017/Citas
    servicio2:
        build: ./microservicio2
        depends_on: 
            - mongo
        environment: 
            - PORT=5000
            - MONGO_URI=mongodb://mongo:27017/Citas
    nginx:
        image: nginx:latest
        ports:
            - "8080:8080"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - servicio1
            - servicio2
    mongo:
        image: mongo